## Converting to and from other data formats

- `to_networkx_graph`(data[, create_using, ...]): Make a NetworkX graph from a known data structure.
- `to_dict_of_dicts`(G[, nodelist, edge_data]): Returns adjacency representation of graph as a dictionary of dictionaries.

In [1]:
import networkx as nx 

d = {0: {1: 1}} # dict-of-dicts single edge (0, 1)
G = nx.Graph(d)

In [6]:
# to_dict_of_dicts
G = nx.Graph()
G.add_edges_from(
    [
        (0, 1, {'weight': 1.0}),
        (1, 2, {'weight': 2.0}),
        (2, 0, {'weight': 1.0}),
    ]
)
d = nx.to_dict_of_dicts(G)
d  

{0: {1: {'weight': 1.0}, 2: {'weight': 1.0}},
 1: {0: {'weight': 1.0}, 2: {'weight': 2.0}},
 2: {1: {'weight': 2.0}, 0: {'weight': 1.0}}}

In [7]:
d = nx.to_dict_of_dicts(G, edge_data=1)
d

{0: {1: 1, 2: 1}, 1: {0: 1, 2: 1}, 2: {1: 1, 0: 1}}

In [8]:

G = nx.MultiGraph()
G.add_edge(0, 1, key='a', weight=1.0)
G.add_edge(0, 1, key='b', weight=5.0)
d = nx.to_dict_of_dicts(G)
d  

{0: {1: {'a': {'weight': 1.0}, 'b': {'weight': 5.0}}},
 1: {0: {'a': {'weight': 1.0}, 'b': {'weight': 5.0}}}}

In [9]:
d[0][1]['b']['weight']

5.0

In [10]:
d = nx.to_dict_of_dicts(G, edge_data=10)
d

{0: {1: 10}, 1: {0: 10}}

- `from_dict_of_dict`(d[, create_using, ...]): Returns a graph from a dictionary of dictionaries.

In [11]:
# from_dict_of_dicts 

dod = {0: {1:{'weight':1}}}
G = nx.from_dict_of_dicts(dod)

## List 

- `to_dict_of_list`(G[, nodelist]): Returns adjacency representation of graph as a dictionary of lists.
- `from_dict_of_list`(d[, create_using]): Returns a graph from a dictionary of lists.
- `to_edgelist`(G[, nodelist]): Returns a list of edges in the graph.
- `from_edgelist`(edgelist[, create_using]): Returns a graph from a list of edges. 

## Numpy 

- `to_numpy_matrix`(G[, nodelist, dtype, order, ...]): Returns the graph adjacency matrix as a NumPy matrix. 

In [12]:
# to numpy matrix 

import numpy as np 
G = nx.Graph([(1, 1)])
A = nx.to_numpy_matrix(G)
A 

matrix([[1.]])

In [13]:
A[np.diag_indices_from(A)] *= 2
A 

matrix([[2.]])

In [14]:
G = nx.MultiDiGraph()
G.add_edge(0, 1, weight=2)
G.add_edge(1, 0)
G.add_edge(2, 2, weight=3)
G.add_edge(2, 2)

nx.to_numpy_matrix(G, nodelist=[0, 1, 2])


matrix([[0., 2., 0.],
        [1., 0., 0.],
        [0., 0., 4.]])

- `to_numpy_array`(G[, nodelist, dtype, order, ...]): Returns the graph adjacency matrix as a NumPy array.

In [15]:
# to_numpy_array 

import numpy as np 
G = nx.Graph([(1, 1)])
A = nx.to_numpy_array(G)
A 

array([[1.]])

In [17]:
A[np.diag_indices_from(A)] *= 2
A

array([[2.]])

In [18]:
G = nx.MultiDiGraph()
G.add_edge(0, 1, weight=2)
G.add_edge(1, 0)
G.add_edge(2, 2, weight=3)
G.add_edge(2, 2)

nx.to_numpy_array(G, nodelist=[0, 1, 2])

array([[0., 2., 0.],
       [1., 0., 0.],
       [0., 0., 4.]])

In [19]:
G = nx.Graph()
G.add_edge(3, 1)
G.add_edge(2, 0)
G.add_edge(2, 1)
G.add_edge(3, 0)
nx.to_numpy_array(G, nodelist=[1, 2, 3])

array([[0., 1., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [20]:
G = nx.Graph()
G.add_edge(0, 1, weight=10)
G.add_edge(1, 2, cost=5)
G.add_edge(2, 3, weight=3, cost=-4.0)
dtype = np.dtype([("weight", int), ("cost", float)])
A = nx.to_numpy_array(G, dtype=dtype, weight=None)
A["weight"]

array([[ 0, 10,  0,  0],
       [10,  0,  1,  0],
       [ 0,  1,  0,  3],
       [ 0,  0,  3,  0]])

In [21]:
G = nx.Graph()
G.add_edge(3, 1, weight=2)
G.add_edge(2, 0, weight=0)
G.add_edge(2, 1, weight=0)
G.add_edge(3, 0, weight=1)
nx.to_numpy_array(G, nonedge=-1.)

array([[-1.,  2., -1.,  1.],
       [ 2., -1.,  0., -1.],
       [-1.,  0., -1.,  0.],
       [ 1., -1.,  0., -1.]])

- `to_numpy_recarray`(G[, nodelist, dtype, order]): Returns the graph adjacency matrix as a NumPy recarray.

In [22]:
# to_numpy_recarray

G = nx.Graph()
G.add_edge(1, 2, weight=7.0, cost=5)
A = nx.to_numpy_recarray(G, dtype=[('weight', float), ('cost', int)])
print(A.weight)

[[0. 7.]
 [7. 0.]]


- `from_numpy_matrix`(A[, parallel_edges, ...]): Returns a graph from numpy matrix.

In [23]:
# from_numpy_matrix 
A = np.array([[1, 1], [2, 1]])
G = nx.from_numpy_matrix(A)

In [24]:
A = np.array([[1, 1], [1, 2]])
G = nx.from_numpy_matrix(A, create_using=nx.MultiGraph)
G[1][1]

AtlasView({0: {'weight': 2}})

In [25]:
A = np.array([[1, 1], [1, 2]])
temp = nx.MultiGraph()
G = nx.from_numpy_matrix(A, parallel_edges=True, create_using=temp)
G[1][1]

AtlasView({0: {'weight': 1}, 1: {'weight': 1}})

In [26]:
dt = [('weight', float), ('cost', int)]
A = np.array([[(1.0, 2)]], dtype=dt)
G = nx.from_numpy_matrix(A)
list(G.edges()) # [(0,0)]

G[0][0]['cost'] # 2

G[0][0]['weight'] # 1.0

1.0


- `from_numpy_array`(A[, parallel_edges, ...]): Returns a graph from a 2D NumPy array.

In [27]:
# from_numpy_array
A = np.array([[1, 1], [2, 1]])
G = nx.from_numpy_array(A)
G.edges(data=True)

EdgeDataView([(0, 0, {'weight': 1}), (0, 1, {'weight': 2}), (1, 1, {'weight': 1})])

In [28]:
A = np.array([[1, 1], [1, 2]])
G = nx.from_numpy_array(A, create_using=nx.MultiGraph)
G[1][1]

AtlasView({0: {'weight': 2}})

In [29]:
A = np.array([[1, 1], [1, 2]])
temp = nx.MultiGraph()
G = nx.from_numpy_array(A, parallel_edges=True, create_using=temp)
G[1][1]

AtlasView({0: {'weight': 1}, 1: {'weight': 1}})

In [30]:
dt = [('weight', float), ('cost', int)]
A = np.array([[(1.0, 2)]], dtype=dt)
G = nx.from_numpy_array(A)
G.edges() # EdgeView([(0, 0)])

G[0][0]['cost'] # 2

G[0][0]['weight'] # 1.0

1.0

## Scipy

- `to_scipy_sparse_array`(G[, nodelist, dtype, ...]): Returns the graph adjacency matrix as a SciPy sparse array.

In [32]:
# to_scipy_sparse_array
G = nx.Graph([(1, 1)])
A = nx.to_scipy_sparse_array(G)
print(A.todense())

A.setdiag(A.diagonal() * 2)
print(A.toarray())

[[1]]
[[2]]


In [35]:
G = nx.MultiDiGraph()
G.add_edge(0, 1, weight=2)
G.add_edge(1, 0)
G.add_edge(2, 2, weight=3)
G.add_edge(2, 2)

S = nx.to_scipy_sparse_array(G, nodelist=[0, 1, 2])
S.todense()

array([[0, 2, 0],
       [1, 0, 0],
       [0, 0, 4]], dtype=int32)

- `to_scipy_sparse_matrix`(G[, nodelist, dtype, ...]): Returns the graph adjacency matrix as a SciPy sparse matrix.
- `from_scipy_sparse_matrix`(A[, ...]): Creates a new graph from an adjacency matrix given as a SciPy sparse matrix.
- `from_scipy_sparse_array`(A[, parallel_edges, ...]): Creates a new graph from an adjacency matrix given as a SciPy sparse array.

In [36]:
# to_scipy_sprse_matrix
G = nx.MultiDiGraph()
G.add_edge(0, 1, weight=2)
G.add_edge(1, 0)
G.add_edge(2, 2, weight=3)
G.add_edge(2, 2)

S = nx.to_scipy_sparse_matrix(G, nodelist=[0, 1, 2])
print(S.todense())

[[0 2 0]
 [1 0 0]
 [0 0 4]]


C:\Users\EonKim\AppData\Local\Temp\ipykernel_18736\3025828366.py:8: DeprecationWarning: 

The scipy.sparse array containers will be used instead of matrices
in Networkx 3.0. Use `to_scipy_sparse_array` instead.
  S = nx.to_scipy_sparse_matrix(G, nodelist=[0, 1, 2])



## Pandas

- `to_pandas_adjacency`(G[, nodelist, dtype, ...]): Returns the graph adjacency matrix as a Pandas DataFrame.

In [37]:
# to_pandas_adjacency
import pandas as pd 
pd.options.display.max_columns = 20 
import numpy as np 
G = nx.Graph([(1, 1)])
df = nx.to_pandas_adjacency(G, dtype=int)
df 

1
1  1

In [39]:
df.values[np.diag_indices_from(df)] *= 2

In [41]:
df

1
1  2

In [42]:
G = nx.MultiDiGraph()
G.add_edge(0, 1, weight=2)
G.add_edge(1, 0)
G.add_edge(2, 2, weight=3)
G.add_edge(2, 2)

nx.to_pandas_adjacency(G, nodelist=[0, 1, 2], dtype=int)

0  1  2
0  0  2  0
1  1  0  0
2  0  0  4

- `from_pandas_adjacency`(df[, create_using]): Returns a graph from Pandas DataFrame.

In [43]:
# from_pandas_adjacency
import pandas as pd 
df = pd.DataFrame([[1, 1, ], [2, 1]])
df

0  1
0  1  1
1  2  1

In [44]:
G = nx.from_pandas_adjacency(df)
G.name = 'Graph from pandas adjacency matrix'
print(nx.info(G))

Graph named 'Graph from pandas adjacency matrix' with 2 nodes and 3 edges


C:\Users\EonKim\AppData\Local\Temp\ipykernel_18736\1275228846.py:3: DeprecationWarning: info is deprecated and will be removed in version 3.0.

  print(nx.info(G))


- `to_pandas_edgelist`(G[, source, target, ...]): Returns the graph edge list as a Pandas DataFrame.

In [46]:
# to_pandas_edgelist
G = nx.Graph(
    [
        ("A", "B", {"cost": 1, "weight": 7}),
        ("C", "E", {"cost": 9, "weight": 10}),
    ]
)
df = nx.to_pandas_edgelist(G, nodelist=["A", "C"])
df[["source", "target", "cost", "weight"]]

source target  cost  weight
0      A      B     1       7
1      C      E     9      10

In [47]:
G = nx.MultiGraph([('A', 'B', {'cost': 1}), ('A', 'B', {'cost': 9})])
df = nx.to_pandas_edgelist(G, nodelist=['A', 'C'], edge_key='ekey')
df[['source', 'target', 'cost', 'ekey']]

source target  cost  ekey
0      A      B     1     0
1      A      B     9     1

- `from_pandas_edgelist`(df[, source, target, ...]): Returns a graph from Pandas DataFrame contraining an edge list.

In [48]:
# from_pandas_edgelist
import pandas as pd 
import numpy as np 

ints = np.random.randint(1, 11, size=(3, 2))
a = ['A', 'B', 'C']
b = ['D', 'A', 'E']

df = pd.DataFrame(ints, columns=['weight', 'cost'])
df[0] = a 
df['b'] = b 
df[['weight', 'cost', 0, 'b']]

weight  cost  0  b
0       1     7  A  D
1       3     5  B  A
2       4     9  C  E

In [49]:
G = nx.from_pandas_edgelist(df, 0, 'b', ['weight', 'cost'])
G['E']['C']['weight'] # 10 
G['E']['C']['cost'] # 9 

edges = pd.DataFrame( 
                     {
                         'source':[0, 1, 2], 
                         'target':[2, 2, 3], 
                         'weight':[3, 4, 5], 
                         'color':['red', 'blue', 'blue']
                     })
G = nx.from_pandas_edgelist(edges, edge_attr=True)
G[0][2]['color']

'red'

In [50]:
edges = pd.DataFrame(
    {
        "source": [0, 1, 2, 0],
        "target": [2, 2, 3, 2],
        "my_edge_key": ["A", "B", "C", "D"],
        "weight": [3, 4, 5, 6],
        "color": ["red", "blue", "blue", "blue"],
    }
)
G = nx.from_pandas_edgelist(
    edges,
    edge_key="my_edge_key",
    edge_attr=["weight", "color"],
    create_using=nx.MultiGraph(),
)
G[0][2]

AtlasView({'A': {'weight': 3, 'color': 'red'}, 'D': {'weight': 6, 'color': 'blue'}})