## Graph Matrix

- `adjacency_matrix`(G[, nodelist, dtype, weight]): Returns adjacency matrix of G.
- `incidence_matrix`(G[, nodelist, edgelist, ...]): Returns incidence matrix of G.

In [6]:
import networkx as nx 

# adjacency matrix 
G = nx.Graph([(1, 1), (1, 2), (2, 3), (3, 1)])
A = nx.adjacency_matrix(G)
print(A.todense())

[[1 1 1]
 [1 0 1]
 [1 1 0]]


C:\Users\EonKim\AppData\Local\Temp\ipykernel_26888\431187968.py:5: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  A = nx.adjacency_matrix(G)


In [7]:
A.setdiag(A.diagonal() * 2)
print(A.todense())

[[2 1 1]
 [1 0 1]
 [1 1 0]]


c:\Users\EonKim\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\sparse\_index.py:146: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)


## Laplacian Matrix 

- `laplacian_matrix`(G[, nodelist, weight]): Returns the Laplacian matrix of G.

The graph Laplacian is the matrix $L=D-A$, where $A$ is the adjacency matrix and $D$ is the diagonal matrix of node degrees.

- `normalized_laplacian_matrix`(G[, nodelist, ...]): Returns the normalized Laplacian matrix of G.
- `directed_laplacian_matrix`(G[, nodelist, ...]): Returns the directed Laplacian matrix of G.
- `directed_combinatorial_laplacian_matrix`(G[, ...]): Returns the directed combinatorial Laplacian matrix of G.

In [22]:
# laplacian_matrix 
G = nx.Graph([(1, 4), (1, 2), (2, 3), (3, 1), (4, 2)])

A = nx.adjacency_matrix(G)
L = nx.laplacian_matrix(G)

C:\Users\EonKim\AppData\Local\Temp\ipykernel_26888\1403629987.py:5: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  A = nx.adjacency_matrix(G)
<class 'networkx.utils.decorators.argmap'> compilation 8:4: FutureWarning: laplacian_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.


In [23]:
G.degree()

DegreeView({1: 3, 4: 2, 2: 3, 3: 2})

In [24]:
A.todense()

matrix([[0, 1, 1, 1],
        [1, 0, 1, 0],
        [1, 1, 0, 1],
        [1, 0, 1, 0]], dtype=int32)

In [25]:
L.todense() + A.todense() # Degree matrix

matrix([[3, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 2]], dtype=int32)

## Algebraic Connectivity 

Algebraic connectivity and Fielder vectors of undirected graphs.

- `algebraic_connectivity`(G[, weight, ...]): Returns the algebraic connectivity of an undirected graph.
- `fiedler_vector`(G[, weight, normalized, tol, ...]): Returns the Fiedler vector of a connected undirected graph.
- `spectral_ordering`(G[, weight, normalized, ...]): Compute the spectal_ordering of a graph.


## Attribute Matrices 

Functions for constructing matrix-like objects from graph attributes.

- `attr_matrix`(G[, edge_attr, node_attr, ...]): Returns a NumPy matrix using attributes from G.

In [30]:
# attr_matrix 
G = nx.Graph()
G.add_edge(0, 1, thickness=1, weight=3)
G.add_edge(0, 2, thickness=2)
nx.attr_matrix(G, rc_order=[0, 1, 2]) # If no ordering is provided, then the ordering will be random (and also, return value).

C:\Users\EonKim\AppData\Local\Temp\ipykernel_26888\929254966.py:5: FutureWarning: attr_matrix will return an numpy.ndarray instead of a numpy.matrix in NetworkX 3.0.
  nx.attr_matrix(G, rc_order=[0, 1, 2])


matrix([[0., 1., 1.],
        [1., 0., 0.],
        [1., 0., 0.]])

In [31]:
nx.attr_matrix(G, edge_attr='thickness', rc_order=[0, 1, 2])

C:\Users\EonKim\AppData\Local\Temp\ipykernel_26888\1543509368.py:1: FutureWarning: attr_matrix will return an numpy.ndarray instead of a numpy.matrix in NetworkX 3.0.
  nx.attr_matrix(G, edge_attr='thickness', rc_order=[0, 1, 2])


matrix([[0., 1., 2.],
        [1., 0., 0.],
        [2., 0., 0.]])

In [32]:
G.nodes[0]['color'] = 'red'
G.nodes[1]['color'] = 'red'
G.nodes[2]['color'] = 'blue'
rc = ['red', 'blue']
nx.attr_matrix(G, node_attr='color', normalized=True, rc_order=rc)

C:\Users\EonKim\AppData\Local\Temp\ipykernel_26888\2673152189.py:5: FutureWarning: attr_matrix will return an numpy.ndarray instead of a numpy.matrix in NetworkX 3.0.
  nx.attr_matrix(G, node_attr='color', normalized=True, rc_order=rc)


matrix([[0.5, 0.5],
        [1. , 0. ]])

In [33]:
nx.attr_matrix(G, edge_attr="weight", node_attr="color", rc_order=rc)

C:\Users\EonKim\AppData\Local\Temp\ipykernel_26888\991580329.py:1: FutureWarning: attr_matrix will return an numpy.ndarray instead of a numpy.matrix in NetworkX 3.0.
  nx.attr_matrix(G, edge_attr="weight", node_attr="color", rc_order=rc)


matrix([[3., 1.],
        [1., 0.]])

- `attr_sparse_matrix`(G[, edge_attr, ...]): Returns a SciPy matrix using attributes from G.

In [34]:
# attr_sparse_matrix 
G = nx.Graph()
G.add_edge(0, 1, thickness=1, weight=3)
G.add_edge(0, 2, thickness=2)
G.add_edge(1, 2, thickness=3)
M = nx.attr_sparse_matrix(G, rc_order=[0, 1, 2])
M.toarray()

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

In [35]:
M = nx.attr_sparse_matrix(G, edge_attr="thickness", rc_order=[0, 1, 2])
M.toarray()

array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]])

In [36]:
G.nodes[0]["color"] = "red"
G.nodes[1]["color"] = "red"
G.nodes[2]["color"] = "blue"
rc = ["red", "blue"]
M = nx.attr_sparse_matrix(G, node_attr="color", normalized=True, rc_order=rc)
M.toarray()

array([[0.33333333, 0.66666667],
       [1.        , 0.        ]])

In [37]:
M = nx.attr_sparse_matrix(G, edge_attr="weight", node_attr="color", rc_order=rc)
M.toarray()

array([[3., 2.],
       [2., 0.]])


## Modularity Matrices 

Modularity matrix of graphs. modularity matrix $B = A - <A>$, where $A$ is the adjacency matrix and $<A>$ is the average adjacency matrix

- `modularity_matrix`(G[, nodelist, weight]): Returns the modularity matrix of G.

$ A_ij - \frac{k_i k_j}{2m} $ where $k_i$ is the degree of node $i$, and where $m$ is the number of edges in the graph.

In [38]:
k = [3, 2, 2, 1, 0]
G = nx.havel_hakimi_graph(k)
B = nx.modularity_matrix(G)

<class 'networkx.utils.decorators.argmap'> compilation 13:5: FutureWarning: modularity_matrix will return a numpy array instead of a matrix in NetworkX 3.0.


In [39]:
B

matrix([[-1.125,  0.25 ,  0.25 ,  0.625,  0.   ],
        [ 0.25 , -0.5  ,  0.5  , -0.25 ,  0.   ],
        [ 0.25 ,  0.5  , -0.5  , -0.25 ,  0.   ],
        [ 0.625, -0.25 , -0.25 , -0.125,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ]])


- `directed_modularity_matrix`(G[, nodelist, weight]): Returns the directed modularity matrix of G.

$ B_{ij} = A_{ij} - k^{out}_i k^{in}_j / m $ where $k^{in}_i$ is the in degree of node $i$, and $k^{out}_j$is the out degree of node $j$, with $m$ the number of edges in the graph. 

In [41]:
# directed modularity matrix 
G = nx.DiGraph()
G.add_edges_from(
    (
        (1, 2),
        (1, 3),
        (3, 1),
        (3, 2),
        (3, 5),
        (4, 5),
        (4, 6),
        (5, 4),
        (5, 6),
        (6, 4),
    )
)
B = nx.directed_modularity_matrix(G)

<class 'networkx.utils.decorators.argmap'> compilation 18:5: FutureWarning: directed_modularity_matrix will return a numpy array instead of a matrix in NetworkX 3.0.


In [42]:
B

matrix([[-0.2,  0.6,  0.8, -0.4, -0.4, -0.4],
        [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0.7,  0.4, -0.3,  0.4, -0.6, -0.6],
        [-0.2, -0.4, -0.2, -0.4,  0.6,  0.6],
        [-0.2, -0.4, -0.2,  0.6, -0.4,  0.6],
        [-0.1, -0.2, -0.1, -0.2,  0.8, -0.2]])


## Spectrum 

Eigenvalue spectrum of graphs.

- `adjacency_spectrum`(G[, weight]): Returns eigenvalues of teh adjacnecy matrix of G.
- `laplacian_spectrum`(G[, weight]): Returns eigenvalues of the Laplacian of G.
- `bethe_hessian_spectrum`(G[, r]): Returns eigenvalues of the Bethe Hessian matrix of G.
- `normalized_laplacian_spectrum`(G[, weight]): Return eigenvalues of the normalized Laplacian of G.
- `modularity_spectrum`(G): Returns eigenvalues of the modularity matrix of G. 